#!/bin/sh
cd ~/.xmonad/

XMONAD_BIN=~/.local/bin
XMONAD_PATH=~/.xmonad/.stack-work/install/x86_64-linux
cd $XMONAD_PATH

TAKE_FIRST_DIRNAME=$(ls -tr|awk 'NR==0; END{print}')

ln -sf $XMONAD_PATH/$TAKE_FIRST_DIRNAME/8.2.2/bin/xmobar $XMONAD_BIN
# ln -sf $XMONAD_PATH/$TAKE_FIRST_DIRNAME/8.2.2/bin/xmonad $XMONAD_BIN
ln -sf ~/.xmonad/xmonad-x86_64-linux $XMONAD_BIN/xmonad
ln -sf $XMONAD_PATH/$TAKE_FIRST_DIRNAME/8.2.2/bin/yeganesh $XMONAD_BIN
