#!/usr/bin/env python

from __future__ import print_function

import os
import re

import yaml


def multiple_replace(args, text):
    regex = re.compile("{{(" + "|".join(re.escape(k) for k in args) + ")}}")
    return regex.sub(lambda mo: args.get(mo.group(1)), text)


def main():
    os.chdir('docker')
    template = open('Dockerfile.in').read()

    for root, dirs, files in os.walk('.'):
        if 'config.yaml' in files:
            args = yaml.load(open(os.path.join(root, 'config.yaml')))
            with open(os.path.join(root, 'Dockerfile'), 'w') as fp:
                print(multiple_replace(args, template), file=fp)


if __name__ == '__main__':
    main()
